[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "peshbeen"
dynamic = ["version"]
description = ""
readme = "README.md"
requires-python = ">=3.10"
license = {text = "Apache-2.0"}
authors = [{name = "Mustafa Aslan", email = "mustafaslan63@gmail.com"}]
keywords = ['nbdev']
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
]
dependencies = ["xgboost", "lightgbm", "catboost", "pandas", "numpy", "scikit-learn","datetime", "hyperopt","statsmodels", "seaborn", "statsforecast",
                          "matplotlib", "window_ops", "cubist", "scipy", "numba", "great_tables", "openpyxl"]

[project.urls]
Repository = "https://github.com/mustafaslanCoto/peshbeen"
Documentation = "https://mustafaslanCoto.github.io/peshbeen/"

[project.entry-points.nbdev]
peshbeen = "peshbeen._modidx:d"

[tool.setuptools.dynamic]
version = {attr = "peshbeen.__version__"}

[tool.setuptools.packages.find]
include = ["peshbeen"]

[tool.nbdev]
lib_name = "peshbeen"
user = "mustafaslanCoto"
branch = "main"
nbs_path = "nbs"
doc_path = "_docs"
recursive = "True"
tst_flags = "notest"
doc_host = "https://mustafaslanCoto.github.io"
doc_baseurl = "/peshbeen"
git_url = "https://github.com/mustafaslanCoto/peshbeen"
lib_path = "peshbeen"
custom_sidebar = "False"